import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-custom-black-background">
        <nav className="p-4">
          <div className="flex">
            <div className="ml-4 flex w-32 flex-1">
              <a href="/" className="text-2xl text-yellow-300">
                Azzuhry
              </a>
              <a href="/" className="text-2xl text-gray-300">
                .github.io
              </a>
            </div>

            <div className="flex flex-1 justify-center gap-14">
              <a
                href="/about"
                className="rounded p-2 font-medium text-gray-300 duration-300 ease-in-out hover:bg-green-400 hover:text-black"
              >
                About
              </a>
              <a
                href="/project"
                className="rounded p-2 font-medium text-gray-300 duration-300 ease-in-out hover:bg-green-400 hover:text-black"
              >
                Projects
              </a>
              <a
                href="#"
                className="rounded p-2 font-medium text-gray-300 duration-300 ease-in-out hover:bg-green-400 hover:text-black"
              >
                Services
              </a>
            </div>

            <div className="flex-1"></div>
          </div>
        </nav>

        {children}

        <footer className="mt-24 flex h-24 flex-row items-center justify-center gap-2 bg-slate-950">
          <h1 className="text-xl text-gray-300">made with</h1>
          <div className="flex flex-row items-center justify-center gap-1">
            <h1 className="text-xl text-cyan-600">TailwindCSS</h1>
            <Image
              src="/svg/icons8-tailwindcss.svg"
              width={32}
              height={32}
              alt="tailwind"
            />
          </div>
        </footer>
      </body>
    </html>
  );
}
